---
sudo: false
dist: trusty
language: generic

env:
  global:
    - PATH="./bin:${PATH}"
    - COMMIT_HASH=${TRAVIS_COMMIT::8}

    - AWS_ACCESS_KEY_ID=AKIAJBCYCKRY5O4H5LRA
    - secure: "LMhSSY4LH7CLLq0fDxfGQGqHM/md9S74veI+taiuML7gb8Hry9sKO5+JnAyCjbJjeGIF8iEq/GsDD8EeSgIvu0BN3dV06lhUptbzrsnFyJAwcZKe4/jsY1b3zcSoTG78sxEXxCj3YWsklK8HNNauyjswY8gHm2S3uuhnhbin0I9gRz/3yFOLgVenGM8PTf9vgiVkBhRtXB7m0b22jiMzlNw/kAar4zIYGJ3DucUx3ITCFxH06YIhOflrubf3am1hb1fkB1pv3PolqnmA4283ShVTtCMdy2VdywDIoY4mZ/5G38kWtU3o6gSFNHd8+dwIcCCCsJpInNWFnxUmkMNSTEFismFHLBtyxpofYiWCaB1AMlXRE2i5iYVCTACYQOVVZ/Wu7hlPKU0T9G16KCo3WswixwKu5k/9g0f4xODGsTsqBAQI6VEhXYd/qvqDgZ6S9biCioVh96TRBRn3h4IvYXLoBtegSyemEHlL6vNuKhkFep2WwWNec0gaOmZu/gbXxZ1eaDUZHjlT2RFDr0HOVd724aH3pocvMudBYvx0iC4CO+7tzNTx3zMsv19O+4MGqP8gIpnjWGngzqw0wV6a5l7+oKnBbxKZLCTm4+O6596KlBg/ybEZ0MVR+KaSK4J9N6fv6eEbYvDiXtQYK4AvDyfO12SIstq8yFIYXu9T45w="

before_install: []

install:
  - set -e
  - bin/install_packer.sh

script:
  - set -e
  - bin/packer_build_release.sh
